### ISSUE TITLE
'Cannot find source file '../../src/sortablejs.module.ts' ' during build output with WebPack

### ISSUE THREAD

**Issue by donskifarrell** [SortableJS/angular-sortablejs#29]
Hi,

I'm using `angular-sortablejs` with WebPack and importing the `SortablejsModule` as:
`import { SortablejsModule } from 'angular-sortablejs';`

then add it to my `@NgModule` with:

`imports: [SharedModule, routing, SortablejsModule],`

The app works correctly, and I can use sortablejs as needed, but I get the following issues during the build output:

```
./~/angular-sortablejs/dist/index.js
Cannot find source file '../index.ts': Error: Can't resolve '../index.ts' in '/Users/XXXX/dev/XXXX/node_modules/angular-sortablejs/dist'
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://127.0.0.1:3000 ./src/main.ts
```

```
./~/angular-sortablejs/dist/src/sortablejs.module.js
Cannot find source file '../../src/sortablejs.module.ts': Error: Can't resolve '../../src/sortablejs.module.ts' in '/Users/XXXX/dev/XXXX/node_modules/angular-sortablejs/dist/src'
 @ ./~/angular-sortablejs/dist/index.js 5:9-43
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://127.0.0.1:3000 ./src/main.ts
```

```
./~/angular-sortablejs/dist/src/sortablejs.directive.js
Cannot find source file '../../src/sortablejs.directive.ts': Error: Can't resolve '../../src/sortablejs.directive.ts' in '/Users/XXXX/dev/XXXX/node_modules/angular-sortablejs/dist/src'
 @ ./~/angular-sortablejs/dist/src/sortablejs.module.js 3:29-62
 @ ./~/angular-sortablejs/dist/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://127.0.0.1:3000 ./src/main.ts
```

Is there any other WebPack config that is needed to stop these errors? Or are there missing files in the `npm` package?

**Comment by smnbbrv** [comment]
Hi @donskifarrell 

what is the version of webpack?

**Comment by donskifarrell** [comment]
I'm using WebPack 2, but this issue was present with WebPack 1 as well.

**Comment by smnbbrv** [comment]
That's weird. Would be helpful to see your webpack config

**Comment by donskifarrell** [comment]
Bit long, but this is after trimming it down. The issue is still present with this config. Thanks for taking a look:

```
const rootPath = require('root-path');
const webpack = require('webpack');
const ContextReplacementPlugin = require('webpack/lib/ContextReplacementPlugin');

const devtoolsConfig = require('./devtools/devtools-config/');

const webpackConfig = {
	devtool: 'inline-source-map',
	bail: false,
	resolve: {
		modules: [
			rootPath('src'),
			'node_modules'
		],
		extensions: ['.ts', '.js', '.json', '.css', '.scss', '.html'],
	},
	entry: {
		'polyfills': './src/polyfills.ts',
		'vendor': './src/vendor.ts',
		'main': './src/main.ts',
	},
	output: {
		path: rootPath('dist'),
		filename: '[name].bundle.js',
		sourceMapFilename: '[name].bundle.map',
		chunkFilename: '[id].chunk.js',
	},
	module: {
		noParse: /node_modules\/onsenui\/js\/onsenui.js/,
		rules: [
			{
				test: /\.ts$/,
				use: {
					loader: 'tslint-loader',
					options: {
						emitErrors: true,
						failOnHint: false,
						resourcePath: 'src',
					},
				},
				exclude: /node_modules/,
				enforce: "pre",
			},
			{
				test: /\.ts$/,
				loader: 'awesome-typescript-loader',
				exclude: [ /\.e2e-spec\.ts$/ ],
			},
			{
				test: /\.js$/,
				loader: 'source-map-loader',
				exclude: [
					// These packages have problems with their source maps;
					rootPath('node_modules/@angular'),
					rootPath('node_modules/@ngrx'),
					rootPath('node_modules/rxjs'),
					rootPath('node_modules/onsenui')
				]
			},
			{
				test: /\.html$/,
				loader: 'raw-loader',
				exclude: [ rootPath('src', 'index.html') ],
			},
			{
				test: /\.css$/,
				loaders: ['css-to-string-loader', 'css-loader']
			},
			{
				test: /\.scss$/,
				exclude: /node_modules/,
				use:  [
					'to-string-loader',
					'css-loader',
					'postcss-loader',
					{
						loader: 'sass-loader',
						options: {
							includePaths: [
								rootPath('src', 'app', 'shared', 'scss'),
							],
						},
					},
				],
			},
			{
				test: /\.svg$/,
				exclude: /node_modules/,
				loader: 'svg-sprite-loader',
			},
			{
				test   : /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9=&.]+)?$/,
				loader : 'file-loader'
			}
		]
	},

	plugins: [

		new ContextReplacementPlugin(
			// The (\\|\/) piece accounts for path separators in *nix and Windows
			/angular(\\|\/)core(\\|\/)src(\\|\/)linker/,
			rootPath('src'), // location of your src
			{
				// your Angular Async Route paths relative to this root directory
			}
		),

		new webpack.LoaderOptionsPlugin({
			debug: devtoolsConfig.LOG_LEVEL === 'DEBUG',
		}),
	],

	devServer: {
		host: devtoolsConfig.WEBPACK_DEV_SERVER_HOST,
		port: devtoolsConfig.WEBPACK_DEV_SERVER_PORT,
		inline: true,
		historyApiFallback: true,
		watchOptions: {
			aggregateTimeout: 300,
			poll: 1000,
		},
		stats: 'verbose',
	}
};

module.exports = webpackConfig;
```

**Comment by smnbbrv** [comment]
Hi @donskifarrell 

your configuration is missing one part which might be essential to remove the error. If you add the empty string to your resolve.extensions this issue should be fixed. That's how it works for my webpack1 config:

```js
extensions: ['', '.js', '.ts']
```

See more here https://webpack.github.io/docs/configuration.html#resolve-extensions

Let me know if this helps.

**Comment by donskifarrell** [comment]
hi @smnbbrv, 

unfortunately that didn't solve it for me. I tried it with my WebPack1 build and also with  myWebPack2 build (although, with WebPack2, the `''` is no longer allowed).

**Comment by smnbbrv** [comment]
well, other config parts look fine to me. I don't think I can help you here... Still, if you find a solution to the problem, keep us posted, maybe it helps others.

Just one last attempt: maybe it is a sourcemaps error, could you try to add the lib to source-map-loader exclusions list?

**Comment by donskifarrell** [comment]
Yep, that last suggestion seems to swallow the warnings up. Thanks!
